version: '3'

services:
  expensive-tracker:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expensive_tracker
    restart: always
    user: root
    expose:
      - 1433
    ports:
      - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: "mysecret1234!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
       - ./db/mssql:/var/opt/mssql